language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g bower
  - npm install -g gulp
  - bower install
  - cd docs
  - bower install
  - cd ..

script:
  - gulp build:docs

notifications:
  emails:
    - yosuke.kurami@gmail.com
